# Generated by Django 4.2 on 2024-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aadhaarusers',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('aadharnumber', models.IntegerField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('verification', models.BooleanField()),
                ('mobilenumber', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='panusers',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('pannumber', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('verification', models.BooleanField()),
                ('mobilenumber', models.IntegerField(max_length=10)),
            ],
        ),
    ]
