# Generated by Django 4.2 on 2024-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarusers',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='panusers',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
