# Generated by Django 4.2 on 2025-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
